apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb
  namespace: imdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imdb
  template:
    metadata:
      labels:
        app: imdb
    spec:
      containers:
        - name: app
          image: ghcr.io/kubernetes101/imdb-app:latest
          imagePullPolicy: Always

          args:
          - --in-memory
          - --zone
          - dev
          - --region
          - dev

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: imdb
  namespace: imdb
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: imdb