apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb
  namespace: imdb
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: imdb
    spec:
      containers:
        - name: app
          args:
          - --in-memory
          - --zone
          - production
          - --region
          - production